const normalize = require('postcss-normalize');
const autoprefixer = require('autoprefixer');
const cssVariables = require('postcss-css-variables');
const { compact } = require('lodash');

const { createBabelConfig } = require('./babel');

const { srcDirectory, excludedPatterns } = require('./variables');

const {
  ifReact,
  ifHot,
  isProd,
  shouldTypeCheck,
  ifProd,
  isDebug,
  isHot,
} = require('./env');

const sassLoaders = [
  {
    loader: 'resolve-url-loader',
    options: {
      sourceMap: true,
    },
  },
  {
    loader: 'sass-loader',
    options: {
      sourceMap: true,
      includePaths: [srcDirectory],
    },
  },
];

const postCssPlugins = [
  autoprefixer,

  // Inlines the value of custom CSS properties
  // for browsers that do not support them
  cssVariables({
    /**
     * `preserve` keeps both the custom property declarations and usages
     * as well as the resolved values as a fallback, so that we can change
     * the values dynamically via JavaScript in browsers that do
     * support custom properties.
     */
    preserve: true,
  }),
];

exports.createGlobalCssLoaders = (isServer = false) => [
  {
    // For the server bundle, we do not want to generate any CSS files,
    // we are only interested in the class name to use in the SSR markup.
    // That's what css-loader/locals does.
    loader: isServer ? 'css-loader/locals' : 'css-loader',
    query: {
      minimize: isProd,
      sourceMap: true,
      modules: false,
    },
  },
  {
    loader: 'postcss-loader',
    options: {
      plugins: [
        // Minimal cross-browser CSS resets, only contains resets relevant
        // for the targeted browsers as specified in `"browserslist"` in `package.json`
        normalize({ forceImport: true }),
        ...postCssPlugins,
      ],
      sourceMap: true,
    },
  },
  ...sassLoaders,
];

exports.createCssModulesLoaders = (isServer = false) => [
  {
    // For the server bundle, we do not want to generate any CSS files,
    // we are only interested in the class name to use in the SSR markup.
    // That's what css-loader/locals does.
    loader: isServer
      ? 'css-loader/locals'
      : ifProd('typings-for-css-modules-loader') || 'css-loader',

    query: {
      minimize: isProd,
      sourceMap: true,
      modules: true,
      camelCase: 'only',

      // Options specific to `typings-for-css-modules-loader`
      namedExport: true,
      banner:
        '// This file is automatically generated.\n// Please do not modify it.\n',

      // Shorten the class name in production bundles to save some bytes
      localIdentName: isProd
        ? '[hash:base64:5]'
        : '[name]__[local]--[hash:base64:5]',
    },
  },
  {
    loader: 'postcss-loader',
    options: {
      sourceMap: true,
      plugins: [
        // @WARN Do not include `normalize`
        ...postCssPlugins,
      ],
    },
  },
  ...sassLoaders,
];

exports.createScriptRules = (isServer = false) => {
  const babelLoader = {
    loader: 'babel-loader',
    options: createBabelConfig(isServer),
  };

  return [
    // Babel
    {
      test: /\.jsx?$/,
      exclude: excludedPatterns,
      use: compact([ifReact(ifHot('react-hot-loader/webpack')), babelLoader]),
    },

    // TypeScript
    {
      test: /\.tsx?$/,
      exclude: excludedPatterns,
      use: compact([
        ifReact(ifHot('react-hot-loader/webpack')),
        babelLoader,
        {
          loader: 'ts-loader',
          options: {
            silent: true,
            transpileOnly: !shouldTypeCheck,
            compilerOptions: {
              noEmitOnError: shouldTypeCheck,
            },
          },
        },
      ]),
    },
  ];
};

exports.globals = {
  __IS_DEBUG__: isDebug,
  __BRANCH__: process.env.BRANCH,
  __COMMIT_ID__: process.env.COMMIT_ID,
  __BASE__: isProd
    ? 'https://hollowverse.com'
    : `http://localhost:${process.env.APP_SERVER_PORT || 3001}`,

  // To avoid issues with cross-origin requests in development,
  // the API endpoint is mapped to an endpoint on the same origin
  // which proxies the requests to the actual defined endpoint
  // The proxy is defined in appServer.ts
  __API_ENDPOINT__: isProd ? process.env.API_ENDPOINT : '/__api',
  'process.env.NODE_ENV': process.env.NODE_ENV,
  isHot,
};
