runtime: custom
env: flex

skip_files:
  - letsEncrypt
  - public
  - designDocs
  - node_modules
  - .log
  - .vscode
  - stats.json
  - client/.babelrc
  - .git

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 6

resources:
  cpu: 1
  memory_gb: 0.9
