FROM node:8.9-alpine

RUN apk update -q

RUN apk add -q --no-cache git

# Native dependencies required to compile the shrink-ray package
RUN apk add -q --no-cache make gcc g++ python

ENV NODE_ENV=development

VOLUME /code
VOLUME /code/node_modules

WORKDIR /code

CMD yarn && yarn dev
